[qldgov:opendata:record]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 0
KV_MODE = json
DATETIME_CONFIG = CURRENT
disabled = false

[qldgov:opendata:hospitals]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 0
KV_MODE = json
DATETIME_CONFIG = CURRENT
disabled = false

[qldgov:opendata:hospital_performance]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 0
KV_MODE = json
DATETIME_CONFIG = CURRENT
disabled = false

[qldgov:opendata:speed_cameras]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 0
KV_MODE = json
DATETIME_CONFIG = CURRENT
disabled = false

[qldgov:opendata:road_crash_locations]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 0
KV_MODE = json
DATETIME_CONFIG = CURRENT
disabled = false

[qldgov:opendata:road_crash_casualties]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 0
KV_MODE = json
DATETIME_CONFIG = CURRENT
disabled = false

[qldgov:opendata:schools]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 0
KV_MODE = json
DATETIME_CONFIG = CURRENT
disabled = false

[qldgov:opendata:transport_centres]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 0
KV_MODE = json
DATETIME_CONFIG = CURRENT
disabled = false

[qldgov:opendata:cadastral_maps]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 0
KV_MODE = json
DATETIME_CONFIG = CURRENT
disabled = false
