[launcher]
version = 0.4.0
description = Collects datasets from the Queensland Government Open Data Portal (and any other CKAN DataStore-backed portal) and indexes them in Splunk as events.

[id]
version = 0.4.0
name = ta_qld_open_data

[install]
build = 1788156704
is_configured = false
state = enabled

[package]
id = ta_qld_open_data
check_for_updates = true

[ui]
label = Queensland Government Open Data Technical Add-on for Splunk
supported_themes = light, dark
is_visible = true

[triggers]
reload.ta_qld_open_data_settings = simple
