[dataset]
python.version = python3
python.required = 3.9, 3.13
interval = 86400
index = default
known_dataset = custom
portal_base_url = https://www.data.qld.gov.au
sourcetype = qldgov:opendata:record
page_size = 1000
