[admin:ta_qld_open_data_configuration]
match = /
members = ta_qld_open_data_settings

[admin:ta_qld_open_data_inputs]
match = /
members = ta_qld_open_data_dataset

[admin_external:ta_qld_open_data_settings]
handlertype = python
python.version = python3
python.required = 3.9, 3.13
handlerfile = ta_qld_open_data_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:ta_qld_open_data_dataset]
handlertype = python
python.version = python3
python.required = 3.9, 3.13
handlerfile = ta_qld_open_data_rh_dataset.py
handleractions = edit, list, remove, create
handlerpersistentmode = true


[admin_external:ta_qld_open_data_open_data_fields]
handlertype = python
python.version = python3
python.required = 3.9, 3.13
handlerfile = qld_open_data_fields_rh.py
handleractions = list
handlerpersistentmode = true

[admin:ta_qld_open_data_open_data_fields_group]
match = /
members = ta_qld_open_data_open_data_fields
