[expose:ta_qld_open_data_settings]
pattern = ta_qld_open_data_settings
methods = POST, GET

[expose:ta_qld_open_data_settings_specified]
pattern = ta_qld_open_data_settings/*
methods = POST, GET, DELETE

[expose:ta_qld_open_data_dataset]
pattern = ta_qld_open_data_dataset
methods = POST, GET

[expose:ta_qld_open_data_dataset_specified]
pattern = ta_qld_open_data_dataset/*
methods = POST, GET, DELETE

[expose:data/indexes]
pattern = data/indexes
methods = GET
